//! Server configuration.
//!
//! Layered with figment: built-in defaults ← TOML file ← `FERRET_*` env
//! vars. The TOML file is `$FERRET_CONFIG`, or `./ferret.toml` if present.
//! On NixOS the file will be generated by the `services.ferret` module.

use std::net::SocketAddr;
use std::path::PathBuf;

use ferret_domain::ProductFamily;
use figment::Figment;
use figment::providers::{Env, Format, Serialized, Toml};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    /// Address the HTTP server binds to.
    pub listen: SocketAddr,
    /// SQLite database file (created on first start).
    pub db_path: PathBuf,
    pub scrape: ScrapeConfig,
    /// Declarative static-HTML sources (generic scraper engine).
    pub sources: Vec<SourceConfig>,
    /// Product family / sibling-model tables (stuffing + outlier signals).
    pub families: Vec<ProductFamily>,
    pub notifications: NotificationsConfig,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            listen: ([0, 0, 0, 0], 4800).into(),
            db_path: "ferret.db".into(),
            scrape: ScrapeConfig::default(),
            sources: Vec::new(),
            families: Vec::new(),
            notifications: NotificationsConfig::default(),
        }
    }
}

/// Global scraping knobs; per-source politeness lives on `SourceConfig`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ScrapeConfig {
    /// A deal priced below `ratio × rolling median` gets `price-outlier`.
    pub outlier_ratio: f64,
    /// Stuffing score at or above this gets `possible-stuffing`.
    pub stuffing_threshold: f64,
    /// Consecutive failures of one source before an ntfy alert fires.
    pub failure_alert_after: u32,
}

impl Default for ScrapeConfig {
    fn default() -> Self {
        Self {
            outlier_ratio: 0.5,
            stuffing_threshold: 0.25,
            failure_alert_after: 5,
        }
    }
}

/// One declarative source: URL + CSS selectors, interpreted by the
/// generic scraper engine. JS-heavy/authenticated sources get hand-written
/// `DealSource` impls instead (later plan).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceConfig {
    /// Stable id, e.g. "hddboard".
    pub id: String,
    /// Page to fetch. `{page}` is replaced by the page number when
    /// `max_pages > 1`.
    pub url: String,
    /// CSS selector for one listing container.
    pub item_selector: String,
    /// Selectors relative to the item container.
    pub title_selector: String,
    pub price_selector: String,
    /// Selector for the link (`href` attribute is taken); defaults to the
    /// item container itself when it is an `<a>`.
    #[serde(default)]
    pub link_selector: Option<String>,
    /// Scrape interval.
    #[serde(default = "default_interval")]
    pub interval_minutes: u64,
    /// Minimum delay between requests to this source.
    #[serde(default = "default_delay")]
    pub delay_ms: u64,
    /// Max concurrent requests to this source.
    #[serde(default = "default_concurrency")]
    pub max_concurrency: usize,
    /// Pages fetched per tick (page 1..=max_pages via `{page}`).
    #[serde(default = "default_pages")]
    pub max_pages: u32,
}

fn default_interval() -> u64 {
    30
}
fn default_delay() -> u64 {
    2000
}
fn default_concurrency() -> usize {
    1
}
fn default_pages() -> u32 {
    1
}

/// Push notifications via ntfy. The whole feature is off when `ntfy_url`
/// is `None` (the default).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct NotificationsConfig {
    /// ntfy server base URL, e.g. `https://notify.zeus.balem.fr`.
    pub ntfy_url: Option<url::Url>,
    /// Topic notifications are published to, e.g. "deals-zeus".
    pub topic: String,
    /// Bearer token for protected topics; read from this file at startup
    /// (agenix-managed on NixOS).
    pub token_file: Option<PathBuf>,
}

/// Load configuration: defaults ← TOML ← env.
pub fn load() -> anyhow::Result<Config> {
    let path = std::env::var("FERRET_CONFIG").unwrap_or_else(|_| "ferret.toml".into());
    let config = Figment::from(Serialized::defaults(Config::default()))
        .merge(Toml::file(path))
        .merge(Env::prefixed("FERRET_").split("__"))
        .extract()?;
    Ok(config)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_are_sane() {
        let config: Config = Figment::from(Serialized::defaults(Config::default()))
            .extract()
            .unwrap();
        assert_eq!(config.listen.port(), 4800);
        assert!(config.sources.is_empty());
        assert!(config.notifications.ntfy_url.is_none());
    }

    #[test]
    fn example_config_parses() {
        let config: Config = Figment::from(Serialized::defaults(Config::default()))
            .merge(Toml::string(include_str!("../ferret.example.toml")))
            .extract()
            .unwrap();
        assert!(!config.sources.is_empty());
        assert!(!config.families.is_empty());
        let src = &config.sources[0];
        assert!(!src.id.is_empty());
        assert!(src.interval_minutes >= 1);
    }
}
